#!/usr/bin/bash
# Toggles the touchpad on and off

# Copyright (C) 2017-2023 Dino Duratović <dinomol at mail dot com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ $1 == "-q" ]]; then
  quiet=1
fi

id=$(xinput | grep -i touchpad | grep -oP "(?<=id=)\d*")

if xinput list-props "$id" | grep -q "Device Enabled.*1$"; then
  xinput disable "$id"
  if [[ -z $quiet ]]; then
    notify-send "Touchpad turned OFF" --icon=input-touchpad
  fi
else
  xinput enable "$id"
  if [[ -z $quiet ]]; then
    notify-send "Touchpad turned ON" --icon=input-touchpad
  fi
fi
